# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_KRSBI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import rosparam
import rospy
import roslib

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TAB = QtWidgets.QTabWidget(self.centralwidget)
        self.TAB.setGeometry(QtCore.QRect(0, 0, 551, 391))
        self.TAB.setObjectName("TAB")
        self.TAB_Main = QtWidgets.QWidget()
        self.TAB_Main.setObjectName("TAB_Main")
        self.TAB.addTab(self.TAB_Main, "")
        self.TAB_Manuvering = QtWidgets.QWidget()
        self.TAB_Manuvering.setObjectName("TAB_Manuvering")
        self.lineEdit = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit.setGeometry(QtCore.QRect(50, 40, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 40, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 40, 51, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 40, 51, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_5.setGeometry(QtCore.QRect(490, 40, 51, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 100, 51, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_7.setGeometry(QtCore.QRect(160, 100, 51, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_8.setGeometry(QtCore.QRect(380, 100, 51, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_9.setGeometry(QtCore.QRect(490, 100, 51, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.TAB_Manuvering)
        self.lineEdit_10.setGeometry(QtCore.QRect(270, 100, 51, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton.setGeometry(QtCore.QRect(30, 310, 231, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 310, 231, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 270, 231, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 270, 231, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 230, 231, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 230, 231, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 190, 231, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.TAB_Manuvering)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 190, 231, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.line_3 = QtWidgets.QFrame(self.TAB_Manuvering)
        self.line_3.setGeometry(QtCore.QRect(0, 150, 551, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        ## START
        # param
        self.h_low = rospy.get_param("/tiang_h_low")
        self.s_low = rospy.get_param("/tiang_s_low")
        self.v_low = rospy.get_param("/tiang_v_low")
        self.h_up = rospy.get_param("/tiang_h_up")
        self.s_up = rospy.get_param("/tiang_s_up")
        self.v_up = rospy.get_param("/tiang_v_up")
        self.brigtnessCam = rospy.get_param("/usb_cam_node/brightness")
        self.exposureCam = rospy.get_param("/usb_cam_node/exposure")


        # TAB IMANGE PROCESSING
        self.TAB.addTab(self.TAB_Manuvering, "")
        self.TAB_ImageProcessing = QtWidgets.QWidget()
        self.TAB_ImageProcessing.setObjectName("TAB_ImageProcessing")
        self.label = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label.setGeometry(QtCore.QRect(130, 0, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_2.setGeometry(QtCore.QRect(130, 180, 31, 16))
        self.label_2.setObjectName("label_2")

        ## SLIDER HUE  LOW
        self.IP_SLD_HueLow = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_HueLow.setGeometry(QtCore.QRect(330, 10, 171, 16))
        self.IP_SLD_HueLow.setMaximum(179)
        self.IP_SLD_HueLow.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_HueLow.setObjectName("IP_SLD_HueLow")

        if int(self.IP_SLD_HueLow.value()) != int(self.h_low):
            print("UPDATE")
            self.IP_SLD_HueLow.setValue(170)
            rosparam.set_param('/tiang_h_low', '170')
        else:
            print("NO UPDATE")
            # pass




        self.IP_SLD_SatLow = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_SatLow.setGeometry(QtCore.QRect(330, 30, 171, 16))
        self.IP_SLD_SatLow.setMaximum(255)
        self.IP_SLD_SatLow.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_SatLow.setObjectName("IP_SLD_SatLow")
        self.IP_SLD_ValLow = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_ValLow.setGeometry(QtCore.QRect(330, 50, 171, 16))
        self.IP_SLD_ValLow.setMaximum(255)
        self.IP_SLD_ValLow.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_ValLow.setObjectName("IP_SLD_ValLow")
        self.IP_SLD_HueUp = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_HueUp.setGeometry(QtCore.QRect(330, 70, 171, 16))
        self.IP_SLD_HueUp.setMaximum(179)
        self.IP_SLD_HueUp.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_HueUp.setObjectName("IP_SLD_HueUp")
        self.IP_SLD_SatUp = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_SatUp.setGeometry(QtCore.QRect(330, 90, 171, 16))
        self.IP_SLD_SatUp.setMaximum(255)
        self.IP_SLD_SatUp.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_SatUp.setObjectName("IP_SLD_SatUp")
        self.IP_SLD_ValUp = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_ValUp.setGeometry(QtCore.QRect(330, 110, 171, 16))
        self.IP_SLD_ValUp.setMaximum(255)
        self.IP_SLD_ValUp.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_ValUp.setObjectName("IP_SLD_ValUp")
        self.line = QtWidgets.QFrame(self.TAB_ImageProcessing)
        self.line.setGeometry(QtCore.QRect(270, 0, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.TAB_ImageProcessing)
        self.line_2.setGeometry(QtCore.QRect(280, 130, 261, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.IP_SLD_Brightness = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_Brightness.setGeometry(QtCore.QRect(330, 170, 171, 16))
        self.IP_SLD_Brightness.setMaximum(255)
        self.IP_SLD_Brightness.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_Brightness.setObjectName("IP_SLD_Brightness")
        self.IP_SLD_Exposure = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_Exposure.setGeometry(QtCore.QRect(330, 150, 171, 16))
        self.IP_SLD_Exposure.setMaximum(255)
        self.IP_SLD_Exposure.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_Exposure.setObjectName("IP_SLD_Exposure")
        self.line_5 = QtWidgets.QFrame(self.TAB_ImageProcessing)
        self.line_5.setGeometry(QtCore.QRect(280, 190, 261, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.IP_BTN_Threshold = QtWidgets.QPushButton(self.TAB_ImageProcessing)
        self.IP_BTN_Threshold.setGeometry(QtCore.QRect(310, 210, 81, 21))
        self.IP_BTN_Threshold.setObjectName("IP_BTN_Threshold")


        self.IP_BTN_Masking = QtWidgets.QPushButton(self.TAB_ImageProcessing)
        self.IP_BTN_Masking.setGeometry(QtCore.QRect(430, 210, 81, 21))
        self.IP_BTN_Masking.setObjectName("IP_BTN_Masking")
        self.IP_SLD_Threshold = QtWidgets.QSlider(self.TAB_ImageProcessing)
        self.IP_SLD_Threshold.setGeometry(QtCore.QRect(330, 240, 171, 20))
        self.IP_SLD_Threshold.setMinimum(1)
        self.IP_SLD_Threshold.setMaximum(100)
        self.IP_SLD_Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.IP_SLD_Threshold.setObjectName("IP_SLD_Threshold")
        self.line_6 = QtWidgets.QFrame(self.TAB_ImageProcessing)
        self.line_6.setGeometry(QtCore.QRect(280, 260, 261, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.IP_BTN_LL = QtWidgets.QPushButton(self.TAB_ImageProcessing)
        self.IP_BTN_LL.setGeometry(QtCore.QRect(290, 280, 241, 17))
        self.IP_BTN_LL.setObjectName("IP_BTN_LL")
        self.IP_BTN_LKR = QtWidgets.QPushButton(self.TAB_ImageProcessing)
        self.IP_BTN_LKR.setGeometry(QtCore.QRect(290, 310, 241, 17))
        self.IP_BTN_LKR.setObjectName("IP_BTN_LKR")
        self.IP_BTN_LMB = QtWidgets.QPushButton(self.TAB_ImageProcessing)
        self.IP_BTN_LMB.setGeometry(QtCore.QRect(290, 340, 241, 17))
        self.IP_BTN_LMB.setObjectName("IP_BTN_LMB")
        self.label_5 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_5.setGeometry(QtCore.QRect(290, 10, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_6.setGeometry(QtCore.QRect(290, 30, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_7.setGeometry(QtCore.QRect(290, 50, 41, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_8.setGeometry(QtCore.QRect(290, 70, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_9.setGeometry(QtCore.QRect(290, 90, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_10.setGeometry(QtCore.QRect(290, 110, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_11.setGeometry(QtCore.QRect(290, 150, 41, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_12.setGeometry(QtCore.QRect(290, 170, 41, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.TAB_ImageProcessing)
        self.label_13.setGeometry(QtCore.QRect(290, 240, 41, 16))
        self.label_13.setObjectName("label_13")
        self.IP_FRAME_Input = QtWidgets.QFrame(self.TAB_ImageProcessing)
        self.IP_FRAME_Input.setGeometry(QtCore.QRect(10, 20, 261, 151))
        self.IP_FRAME_Input.setFrameShape(QtWidgets.QFrame.Box)
        self.IP_FRAME_Input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IP_FRAME_Input.setMidLineWidth(0)
        self.IP_FRAME_Input.setObjectName("IP_FRAME_Input")



        self.IP_FRAME_Output = QtWidgets.QFrame(self.TAB_ImageProcessing)
        self.IP_FRAME_Output.setGeometry(QtCore.QRect(10, 200, 261, 161))
        self.IP_FRAME_Output.setFrameShape(QtWidgets.QFrame.Box)
        self.IP_FRAME_Output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IP_FRAME_Output.setMidLineWidth(0)
        self.IP_FRAME_Output.setObjectName("IP_FRAME_Output")
        self.IP_lcdNumber_HueLow = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_HueLow.setGeometry(QtCore.QRect(500, 10, 41, 16))
        self.IP_lcdNumber_HueLow.setObjectName("IP_lcdNumber_HueLow")
        self.IP_lcdNumber_VaLow = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_VaLow.setGeometry(QtCore.QRect(500, 50, 41, 16))
        self.IP_lcdNumber_VaLow.setObjectName("IP_lcdNumber_VaLow")
        self.IP_lcdNumber_SatLow = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_SatLow.setGeometry(QtCore.QRect(500, 30, 41, 16))
        self.IP_lcdNumber_SatLow.setObjectName("IP_lcdNumber_SatLow")
        self.IP_lcdNumber_HueUp = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_HueUp.setGeometry(QtCore.QRect(500, 70, 41, 16))
        self.IP_lcdNumber_HueUp.setObjectName("IP_lcdNumber_HueUp")
        self.IP_lcdNumber_ValUp = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_ValUp.setGeometry(QtCore.QRect(500, 110, 41, 16))
        self.IP_lcdNumber_ValUp.setObjectName("IP_lcdNumber_ValUp")
        self.IP_lcdNumber_SatUp = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_SatUp.setGeometry(QtCore.QRect(500, 90, 41, 16))
        self.IP_lcdNumber_SatUp.setObjectName("IP_lcdNumber_SatUp")
        self.IP_lcdNumber_Exposure = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_Exposure.setGeometry(QtCore.QRect(500, 150, 41, 16))
        self.IP_lcdNumber_Exposure.setObjectName("IP_lcdNumber_Exposure")
        self.IP_lcdNumber_Brightness = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_Brightness.setGeometry(QtCore.QRect(500, 170, 41, 16))
        self.IP_lcdNumber_Brightness.setObjectName("IP_lcdNumber_Brightness")
        self.IP_lcdNumber_Threshold = QtWidgets.QLCDNumber(self.TAB_ImageProcessing)
        self.IP_lcdNumber_Threshold.setGeometry(QtCore.QRect(500, 240, 41, 16))
        self.IP_lcdNumber_Threshold.setObjectName("IP_lcdNumber_Threshold")
        self.TAB.addTab(self.TAB_ImageProcessing, "")
        self.TAB_Komunikasi = QtWidgets.QWidget()
        self.TAB_Komunikasi.setObjectName("TAB_Komunikasi")
        self.TAB.addTab(self.TAB_Komunikasi, "")
        self.TAB_Packaging = QtWidgets.QWidget()
        self.TAB_Packaging.setObjectName("TAB_Packaging")
        self.TAB.addTab(self.TAB_Packaging, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TAB.setCurrentIndex(2)
        self.IP_SLD_HueLow.sliderMoved['int'].connect(self.IP_lcdNumber_HueLow.display)
        self.IP_SLD_SatLow.sliderMoved['int'].connect(self.IP_lcdNumber_SatLow.display)
        self.IP_SLD_ValLow.sliderMoved['int'].connect(self.IP_lcdNumber_VaLow.display)
        self.IP_SLD_HueUp.sliderMoved['int'].connect(self.IP_lcdNumber_HueUp.display)
        self.IP_SLD_SatUp.sliderMoved['int'].connect(self.IP_lcdNumber_SatUp.display)
        self.IP_SLD_ValUp.sliderMoved['int'].connect(self.IP_lcdNumber_ValUp.display)
        self.IP_SLD_Exposure.sliderMoved['int'].connect(self.IP_lcdNumber_Exposure.display)
        self.IP_SLD_Threshold.sliderMoved['int'].connect(self.IP_lcdNumber_Threshold.display)
        self.IP_SLD_Brightness.sliderMoved['int'].connect(self.IP_lcdNumber_Brightness.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TAB.setTabText(self.TAB.indexOf(self.TAB_Main), _translate("MainWindow", "Page"))
        self.pushButton.setText(_translate("MainWindow", "G"))
        self.pushButton_2.setText(_translate("MainWindow", "H"))
        self.pushButton_3.setText(_translate("MainWindow", "F"))
        self.pushButton_4.setText(_translate("MainWindow", "E"))
        self.pushButton_5.setText(_translate("MainWindow", "D"))
        self.pushButton_6.setText(_translate("MainWindow", "C"))
        self.pushButton_7.setText(_translate("MainWindow", "B"))
        self.pushButton_8.setText(_translate("MainWindow", "A"))
        self.TAB.setTabText(self.TAB.indexOf(self.TAB_Manuvering), _translate("MainWindow", "Page"))
        self.label.setText(_translate("MainWindow", "INPUT"))
        self.label_2.setText(_translate("MainWindow", "OUTPUT"))
        self.IP_BTN_Threshold.setText(_translate("MainWindow", "Threshold"))
        self.IP_BTN_Masking.setText(_translate("MainWindow", "Masking"))
        self.IP_BTN_LL.setText(_translate("MainWindow", "Lomba Lari"))
        self.IP_BTN_LKR.setText(_translate("MainWindow", "Lomba Kerjasama Robot"))
        self.IP_BTN_LMB.setText(_translate("MainWindow", "Lomba Menggiring Bola"))
        self.label_5.setText(_translate("MainWindow", "Hue Low"))
        self.label_6.setText(_translate("MainWindow", "Sat Low"))
        self.label_7.setText(_translate("MainWindow", "Val Low"))
        self.label_8.setText(_translate("MainWindow", "Hue Up"))
        self.label_9.setText(_translate("MainWindow", "Sat Up"))
        self.label_10.setText(_translate("MainWindow", "Val Up"))
        self.label_11.setText(_translate("MainWindow", "Exposure"))
        self.label_12.setText(_translate("MainWindow", "Brightness"))
        self.label_13.setText(_translate("MainWindow", "Threshold"))
        self.TAB.setTabText(self.TAB.indexOf(self.TAB_ImageProcessing), _translate("MainWindow", "Page"))
        self.TAB.setTabText(self.TAB.indexOf(self.TAB_Komunikasi), _translate("MainWindow", "Page"))
        self.TAB.setTabText(self.TAB.indexOf(self.TAB_Packaging), _translate("MainWindow", "Page"))


import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)


    while True:
        MainWindow.show()
        print(ui.IP_SLD_HueLow.value())
        sys.exit(app.exec_())
